name: CD API

on:
    push:
      branches:
        - main
        - dev
      paths:
        - 'apps/api/**'
        - 'packages/**'

permissions:
  contents: read
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Deploy to AWS
jobs:
    # changed-files-check:
    #   uses: ./.github/workflows/changed-files.yaml
    #   with:
    #     files: |
    #       package.json
    #       apps/api/**
    deploy-api:
      runs-on: ubuntu-latest  
      steps:
        - uses: ./.github/actions/setup-pnpm-node
        - name: Lint API
          run: pnpm turbo lint --filter api
        - name: Type-check API
          run: pnpm turbo type-check --filter api
        - name: Build API
          run: pnpm turbo build --filter api
        # - name: Deploy API
        #   run: |
        #     pnpm turbo run deploy --filter api