name: CI

on:
    push:
    pull_request:

permissions:
  contents: read
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Add jobs for testing
jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - uses: ./.github/actions/setup-pnpm-node
        - name: Lint
          run: pnpm turbo lint --filter frontend --filter api --filter mobileApp
    type-check:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - uses: ./.github/actions/setup-pnpm-node
        - name: Type Check
          run: pnpm turbo type-check --filter frontend --filter api --filter mobileApp
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - uses: ./.github/actions/setup-pnpm-node
        - name: Build
          run: pnpm turbo build --filter frontend --filter api --filter mobileApp
    ci-status-check:
        if: always() && !cancelled()
        timeout-minutes: 1
        runs-on: ubuntu-latest
        needs: [lint, type-check, build]
        steps:
        - name: Fail job if any needs failed
          if: contains(needs.*.result, 'failure')
          run: exit 1